### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by AlexDaniel** [FROGGS/p6-Games-BubbleBreaker#7]
I see these `use` statements:

```
use SDL::Video;
use SDL::Surface;
use SDL::App;
use SDL::SFont;
```

But it looks like there are no such modules.

**Comment by 2colours** [comment]
Fixed with https://github.com/raku-community-modules/Games-BubbleBreaker/commit/271761159b8aecabfaf68983b29fc69fb703bc26
